// NEW-FU-272 (Phase 50): two coordinated data-model additions:
//
//   1. courses.venue_exempt — capstone/graduation-project courses don't
//      have venues by design (instructor + team meet online or wherever).
//      The flag tells the conflict engine to skip every venue-related
//      rule (R-04, R-10, R-11, R-12) for these courses, instead of us
//      having to special-case the course codes in each rule.
//
//   2. venues.type extended with 'Multipurpose' — some real KFUPM rooms
//      are used as BOTH lecture halls AND labs (e.g., 22-334 hosts SWE 363
//      lectures AND SWE 206 labs). Forcing a single type creates fake
//      R-11 / R-12 firings either way. 'Multipurpose' captures the real
//      capability and is treated as valid for both Lec and Lab sections.
//
// Both additions are zero-data-loss: existing rows stay valid (default
// venue_exempt=FALSE, existing LectureHall/Laboratory venues unchanged).
// Down reverses cleanly.

async function up(client) {
  // ─ 1. courses.venue_exempt ───────────────────────────────────────────────
  await client.query(`
    ALTER TABLE courses
      ADD COLUMN venue_exempt BOOLEAN NOT NULL DEFAULT FALSE
  `);

  // ─ 2. venues.type CHECK extended to allow 'Multipurpose' ────────────────
  // Postgres can't ALTER a CHECK in place — drop and re-add. The constraint
  // name was auto-generated by the original `CHECK (type IN ...)` in
  // migration 004; PG names those `<table>_<col>_check`.
  await client.query(`
    ALTER TABLE venues
      DROP CONSTRAINT IF EXISTS venues_type_check
  `);
  await client.query(`
    ALTER TABLE venues
      ADD CONSTRAINT venues_type_check
      CHECK (type IN ('LectureHall', 'Laboratory', 'Multipurpose'))
  `);
}

async function down(client) {
  // Reverse in opposite order. The CHECK rollback assumes no rows have
  // type='Multipurpose' at this point — the caller is expected to
  // re-classify those before invoking down, otherwise the new CHECK
  // would refuse to apply.
  await client.query(`
    ALTER TABLE venues
      DROP CONSTRAINT IF EXISTS venues_type_check
  `);
  await client.query(`
    ALTER TABLE venues
      ADD CONSTRAINT venues_type_check
      CHECK (type IN ('LectureHall', 'Laboratory'))
  `);
  await client.query(`
    ALTER TABLE courses
      DROP COLUMN IF EXISTS venue_exempt
  `);
}

module.exports = { up, down };
